name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cabal: [latest]
        ghc: ["8.6", "8.8", "8.10"]
        exclude:
          - os: macOS-latest
            ghc: "8.8"
          - os: macOS-latest
            ghc: "8.6"
          - os: windows-latest
            ghc: "8.6"
          - os: windows-latest
            ghc: "8.8"
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/setup-haskell@v1.1
        id: setup-haskell
        name: setup
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - uses: actions/cache@v1
        name: cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-cabal-store-
      - name: build ki
        run: ./do build ki
      - name: test ki
        run: ./do test ki
      - name: build ki-mtl
        run: ./do build ki-mtl
