name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cabal: [latest]
        ghc: ["8.6", "8.8", "8.10"]
        exclude:
          - os: macOS-latest
            ghc: "8.8"
          - os: macOS-latest
            ghc: "8.6"
          - os: windows-latest
            ghc: "8.6"
          - os: windows-latest
            ghc: "8.8"

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1.1
      id: setup-haskell
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store

    - uses: actions/cache@v1
      name: Cache ./dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-dist-newstyle

    - name: cabal update
      run: |
        cabal update

    - name: cabal build
      run: |
        cabal build all --enable-tests

    - name: cabal test
      run: |
        cabal test all
