name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ["8.10", "8.8", "8.6"]
        include:
          - os: macOS-latest
            ghc: "8.10"
          - os: windows-latest
            ghc: "8.10"

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/cache@v2
        name: Cache GHC on MacOS
        if: matrix.os == 'macOS-latest'
        with:
          path: |
            ~/.ghcup/bin
            ~/.ghcup/ghc
          key: ${{ runner.os }}-${{ matrix.ghc }}-ghc

      - uses: actions/setup-haskell@v1.1
        id: setup-haskell
        name: Setup
        with:
          ghc-version: ${{ matrix.ghc }}

      - uses: actions/cache@v2
        name: Cache cabal store
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store-${{ hashFiles('cabal.project') }}-${{ hashFiles('**/*.cabal') }}

      - uses: actions/cache@v2
        name: Cache build directory
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-dist-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-dist-

      - name: Build ki-indef
        run: cabal build ki:lib:ki-indef --constraint "ki +build-tests" --disable-optimization --enable-tests

      - name: Build ki
        run: cabal build ki:lib:ki --constraint "ki +build-tests" --disable-optimization --enable-tests

      - name: Build tests
        run: cabal build ki:test:tests --constraint "ki +build-tests" --disable-optimization --enable-tests

      - name: Run tests
        run: cabal run ki:test:tests --constraint "ki +build-tests" --disable-optimization --enable-tests
